### PR TITLE
converted all names to snake_case format

### PR DESCRIPTION
**Pull request by armed**
nvim api using snake case, I believe its a good idea to keep same style. Also added stylua config file

### CODE REVIEW

**Comment by armed** [comment]
Not sure about enforcing 80 chars column width though.

**Comment by julienvincent** [comment]
I think enforcing 120 column with is better than 80. 80 is a good practice but I think 120 is a more lenient enforcement

**Review by julienvincent — APPROVED** [review]

**Comment by julienvincent** [comment]
But otherwise looks good thanks!

**Review by julienvincent — COMMENTED** [review]
Oh, can you update the README too

**Comment by armed** [comment]
- 120 chars line length
- applied formatting to all files according to stylua settings
- added luarc with few globals to suppress diagnostics errors
- updated readme.md

**Review by julienvincent — APPROVED** [review]

**Pull request merged**
